name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --prefer-dist

      - name: Run PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php --allow-risky=yes --dry-run --diff

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

  tests:
    needs: analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.1', '7.2', '7.3', '7.4', '8.0', '8.1']
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: pcov

      - name: Install dependencies
        run: composer install --no-interaction --no-suggest --prefer-dist

      - name: Execute tests via PHPUnit
        if: ${{ matrix.php-version != '8.1' }}
        run: vendor/bin/phpunit -d memory_limit=512M

      - name: Execute tests via PHPUnit with coverage
        if: ${{ matrix.php-version == '8.1' }}
        run: vendor/bin/phpunit -d memory_limit=512M --coverage-clover build/logs/clover.xml

      - name: Upload coverage results to Coveralls
        if: ${{ matrix.php-version == '8.1' }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=build/logs/clover.xml -v
